### ISSUE TITLE
how to compute similar items?

### ISSUE THREAD

**Issue by richardxy** [magsol/pyspark-lsh#1]
Hi,
Thanks for writing the package. It seems to me that the compute function of LSH model is still missing. In the Scala counterpart, the compute function finds the similar items to the input entry. 

thanks,
Richard

**Comment by magsol** [comment]
You are correct--I was pulled onto other projects and have not had time to complete this one. It is definitely still something I want to finish. Feel free to submit a pull request if you're interested in doing it :) Otherwise I'll get to it soon.

**Comment by aman010** [comment]
is'nt "if c > 0" should be "if c >= 0" and scipy jaccard similarity is for binary vectors though it works
well , it should be (1- distance.pdist(...)) .

 
thanks,Aman

**Comment by magsol** [comment]
What lines are you referring to?

**Comment by aman010** [comment]
sorry i meant "len(x[1]) > c" should "len(x[1]) >= c" 

thanks

**Comment by magsol** [comment]
I'm still not sure what file / line number you're referring to.

**Comment by magsol** [comment]
Closing this issue as the question was never clarified.
